# Generated by Django 3.2.4 on 2021-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.UniqueConstraint(fields=('phone_number', 'user'), name='unique number'),
        ),
    ]
