# Generated by Django 3.2.4 on 2021-06-17 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_myuser_unique number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myuser',
            name='unique number',
        ),
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together={('phone_number', 'user')},
        ),
    ]
